import { mkdirSync, writeFileSync } from 'fs';
import { readdir } from 'fs/promises';
import path from 'path';
import type { Plugin } from 'vite';

/**
 * Vite plugin that dynamically discovers mockup components and writes them to
 * a generated module under src/.generated. Uses fast-glob for initial
 * discovery and a dedicated chokidar watcher (with awaitWriteFinish) for
 * reliable file monitoring.
 *
 * Adapted from the component gallery plugin in pid2
 * (pkg/pid2/src/lib/vite/componentGalleryPlugin.ts).
 *
 * Generated module: "src/.generated/mockup-components.ts"
 * Exports: { modules: Record<string, () => Promise<Record<string, unknown>>> }
 *
 * When mockup files are added or removed, the generated module is rewritten.
 * Vite's normal file watching handles the update. If a relevant preview
 * request still returns 404 before the watcher settles, the dev server rescans
 * automatically. Individual file edits are handled by React Fast Refresh and
 * imported CSS HMR (no manual CSS invalidation needed).
 */

const MOCKUPS_DIR = 'src/components/mockups';
const GENERATED_MODULE = 'src/.generated/mockup-components.ts';

interface DiscoveredComponent {
  globKey: string;
  importPath: string;
}

export function mockupPreviewPlugin(): Plugin {
  let root = '';
  let currentSource = '';
  let watcher: { close: () => Promise<void> } | null = null;

  function getMockupsAbsDir(): string {
    return path.join(root, MOCKUPS_DIR);
  }

  function getGeneratedModuleAbsPath(): string {
    return path.join(root, GENERATED_MODULE);
  }

  function isMockupFile(absolutePath: string): boolean {
    const rel = path.relative(getMockupsAbsDir(), absolutePath);
    return (
      !rel.startsWith('..') && !path.isAbsolute(rel) && rel.endsWith('.tsx')
    );
  }

  function isPreviewTarget(relativeToMockups: string): boolean {
    return relativeToMockups
      .split(path.sep)
      .every((segment) => !segment.startsWith('_'));
  }

  async function discoverComponents(): Promise<Array<DiscoveredComponent>> {
    const files: string[] = [];
    const walk = async (directory: string): Promise<void> => {
      const entries = await readdir(directory, { withFileTypes: true });
      await Promise.all(entries.map(async (entry) => {
        const absolutePath = path.join(directory, entry.name);
        if (entry.isDirectory()) {
          if (!entry.name.startsWith('_')) await walk(absolutePath);
        } else if (entry.name.endsWith('.tsx') && !entry.name.startsWith('_')) {
          files.push(path.relative(root, absolutePath).split(path.sep).join('/'));
        }
      }));
    };

    try {
      await walk(getMockupsAbsDir());
    } catch (error: unknown) {
      if ((error as NodeJS.ErrnoException)?.code !== 'ENOENT') throw error;
    }

    return files.map((f) => ({
      globKey: './' + f.slice('src/'.length),
      importPath: path.posix.relative('src/.generated', f),
    }));
  }

  function generateSource(components: Array<DiscoveredComponent>): string {
    const entries = components
      .map(
        (c) =>
          `  ${JSON.stringify(c.globKey)}: () => import(${JSON.stringify(c.importPath)})`,
      )
      .join(',\n');

    return [
      '// This file is auto-generated by mockupPreviewPlugin.ts.',
      'type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;',
      'export const modules: ModuleMap = {',
      entries,
      '};',
      '',
    ].join('\n');
  }

  function shouldAutoRescan(pathname: string): boolean {
    return (
      pathname.includes('/components/mockups/') ||
      pathname.includes('/.generated/mockup-components')
    );
  }

  let refreshInFlight = false;
  let refreshQueued = false;

  async function refresh(): Promise<boolean> {
    if (refreshInFlight) {
      refreshQueued = true;
      return false;
    }

    refreshInFlight = true;
    let changed = false;
    try {
      const components = await discoverComponents();
      const newSource = generateSource(components);
      if (newSource !== currentSource) {
        currentSource = newSource;
        const generatedModuleAbsPath = getGeneratedModuleAbsPath();
        mkdirSync(path.dirname(generatedModuleAbsPath), { recursive: true });
        writeFileSync(generatedModuleAbsPath, currentSource);
        changed = true;
      }
    } finally {
      refreshInFlight = false;
    }

    if (refreshQueued) {
      refreshQueued = false;
      const followUp = await refresh();
      return changed || followUp;
    }

    return changed;
  }

  async function onFileAddedOrRemoved(): Promise<void> {
    await refresh();
  }

  return {
    name: 'mockup-preview',
    enforce: 'pre',

    configResolved(config) {
      root = config.root;
    },

    async buildStart() {
      await refresh();
    },

    async configureServer(viteServer) {
      await refresh();

      const mockupsAbsDir = getMockupsAbsDir();
      mkdirSync(mockupsAbsDir, { recursive: true });

      viteServer.middlewares.use((req, res, next) => {
        const requestUrl = new URL(req.url ?? '/', 'http://127.0.0.1');
        const pathname = requestUrl.pathname;
        const originalEnd = res.end.bind(res);

        res.end = ((...args: Parameters<typeof originalEnd>) => {
          if (res.statusCode === 404 && shouldAutoRescan(pathname)) {
            void refresh();
          }
          return originalEnd(...args);
        }) as typeof res.end;

        next();
      });
    },

    async closeWatcher() {
      if (watcher) {
        await watcher.close();
      }
    },
  };
}
