// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/login-forms/Login2026.tsx": () => import("../components/mockups/login-forms/Login2026.tsx"),
  "./components/mockups/siswa-dashboard/Mobile.tsx": () => import("../components/mockups/siswa-dashboard/Mobile.tsx"),
  "./components/mockups/siswa-dashboard/Web.tsx": () => import("../components/mockups/siswa-dashboard/Web.tsx"),
  "./components/mockups/guru-dashboard/Mobile.tsx": () => import("../components/mockups/guru-dashboard/Mobile.tsx"),
  "./components/mockups/guru-dashboard/Web.tsx": () => import("../components/mockups/guru-dashboard/Web.tsx")
};
